# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('task', models.CharField(max_length=50, null=True)),
                ('task_status', models.CharField(default='START', max_length=100)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('service', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
